### ISSUE TITLE
79页下方：关于istio-proxy替换pause容器

### ISSUE THREAD

**Issue by peacocktrain** [seflerZ/book-istio-in-action#2]
ip跟pod绑定是k8s原生特性，这里并不能证明istio替换了pause容器，
并且istio-proxy没有替换pause，如果要替换pause可以通过kubelet的参数设置~可以到kubelet --help 看下

**Comment by seflerZ** [comment]
经查证，pause 容器并没有被替换，仍然存在，因此书中表述有误，没有替换，只是利用。此问题将会在第二版中修正，届时您将免费获取到新版本的书籍。

感谢您的反馈。

**Comment by seflerZ** [comment]
已经在第二版中修正

**Comment by seflerZ** [comment]
closed
